name: Minify BipPip JavaScript Files

on:
  push:
    branches: [main]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Minify JavaScript files
        run: |
          find ./BipPip -type f -name 'BipPip-*.js' -exec bash -c 'npx uglify-js "$1" -o "${1%.js}.min.js" --compress --mangle' -- {} \;

      - name: Commit and push minified files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./BipPip/*.min.js
          git commit -m "Minify JavaScript files in BipPip folder on push" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }} HEAD:main
